#!/bin/sh

# start some nice programs
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
  for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

[[ -f ~/.Xresources ]] && xrdb -merge ~/.Xresources

# xset -dpms &
# xset s off &
# xset -b &

# Custom window compositor
xcompmgr &

# Set background color requires `hsetroot`
hsetroot -solid "#413e33"

# Configure applications under X, requires `xsettingsd`
systemctl --user start xsettingsd.service

# Hide cursor
unclutter --fork --timeout=3 --jitter=3 --exclude-root

exec awesome -a
