#!/bin/sh
setxkbmap -option shift:both_capslock
# pactl set-sink-volume 0 65536

# start some nice programs
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
  for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

# xset -dpms &
xset s off &
xset -b &
xsetroot -solid "#575244"

[[ -f ~/.Xresources ]] && xrdb -merge -I$HOME ~/.Xresources

exec awesome -a
