#!/bin/sh

# start some nice programs
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
  for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

[[ -f ~/.Xresources ]] && xrdb -merge ~/.Xresources

# xset -dpms &
# xset s off &
# xset -b &

# Set background color
# requires hsetroot
xcompmgr &
hsetroot -solid "#413e33"

# Hide cursor
unclutter --fork --timeout=3 --jitter=3 --exclude-root

exec awesome -a
